//
// Generated by Bluespec Compiler, version 2025.01.1-14-g36da7029 (build 36da7029)
//
// On Sun Jan 18 16:30:32 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_start                      O     1 const
// getResult                      O    80 reg
// RDY_getResult                  O     1 reg
// busy                           O     1 reg
// RDY_busy                       O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// start_x_init                   I    24
// start_y_init                   I    24
// start_z_init                   I    24
// start_mode                     I     2
// EN_start                       I     1
// EN_getResult                   I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCORDIC(CLK,
		RST_N,

		start_x_init,
		start_y_init,
		start_z_init,
		start_mode,
		EN_start,
		RDY_start,

		EN_getResult,
		getResult,
		RDY_getResult,

		busy,
		RDY_busy);
  input  CLK;
  input  RST_N;

  // action method start
  input  [23 : 0] start_x_init;
  input  [23 : 0] start_y_init;
  input  [23 : 0] start_z_init;
  input  [1 : 0] start_mode;
  input  EN_start;
  output RDY_start;

  // actionvalue method getResult
  input  EN_getResult;
  output [79 : 0] getResult;
  output RDY_getResult;

  // value method busy
  output busy;
  output RDY_busy;

  // signals for module outputs
  wire [79 : 0] getResult;
  wire RDY_busy, RDY_getResult, RDY_start, busy;

  // register busy_reg
  reg busy_reg;
  wire busy_reg$D_IN, busy_reg$EN;

  // register state
  reg [79 : 0] state;
  wire [79 : 0] state$D_IN;
  wire state$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_do_iteration;

  // inputs to muxes for submodule ports
  wire [79 : 0] MUX_state$write_1__VAL_1, MUX_state$write_1__VAL_2;

  // remaining internal signals
  reg [23 : 0] CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3,
	       CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4;
  wire [31 : 0] IF_IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BI_ETC___d36;
  wire [23 : 0] IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_26214_ETC___d29,
		state_BITS_55_TO_32_SRA_state_BITS_7_TO_3_4___d15,
		state_BITS_55_TO_32__q2,
		state_BITS_79_TO_56_3_SRA_state_BITS_7_TO_3_4___d19,
		state_BITS_79_TO_56__q1;
  wire IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12;

  // action method start
  assign RDY_start = 1'd1 ;

  // actionvalue method getResult
  assign getResult = state ;
  assign RDY_getResult = state[0] ;

  // value method busy
  assign busy = busy_reg ;
  assign RDY_busy = 1'd1 ;

  // rule RL_do_iteration
  assign WILL_FIRE_RL_do_iteration = busy_reg && !state[0] ;

  // inputs to muxes for submodule ports
  assign MUX_state$write_1__VAL_1 =
	     { start_x_init,
	       start_y_init,
	       start_z_init,
	       5'd0,
	       start_mode,
	       1'd0 } ;
  assign MUX_state$write_1__VAL_2 =
	     { IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 ?
		 state[79:56] +
		 state_BITS_55_TO_32_SRA_state_BITS_7_TO_3_4___d15 :
		 state[79:56] -
		 state_BITS_55_TO_32_SRA_state_BITS_7_TO_3_4___d15,
	       IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 ?
		 state[55:32] -
		 state_BITS_79_TO_56_3_SRA_state_BITS_7_TO_3_4___d19 :
		 state[55:32] +
		 state_BITS_79_TO_56_3_SRA_state_BITS_7_TO_3_4___d19,
	       IF_IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BI_ETC___d36 } ;

  // register busy_reg
  assign busy_reg$D_IN = EN_start ;
  assign busy_reg$EN =
	     WILL_FIRE_RL_do_iteration && state[7:3] == 5'd19 || EN_start ;

  // register state
  assign state$D_IN =
	     EN_start ? MUX_state$write_1__VAL_1 : MUX_state$write_1__VAL_2 ;
  assign state$EN = WILL_FIRE_RL_do_iteration || EN_start ;

  // remaining internal signals
  assign IF_IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BI_ETC___d36 =
	     { IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 ?
		 state[31:8] +
		 IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_26214_ETC___d29 :
		 state[31:8] -
		 IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_26214_ETC___d29,
	       state[7:3] + 5'd1,
	       state[2:1],
	       state[7:3] == 5'd19 } ;
  assign IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 =
	     (state[2:1] == 2'd1) ?
	       (state[55:32] ^ 24'h800000) > 24'd8388608 :
	       state[31] ;
  assign IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_26214_ETC___d29 =
	     (state[2:1] == 2'd2) ?
	       CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 :
	       CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 ;
  assign state_BITS_55_TO_32_SRA_state_BITS_7_TO_3_4___d15 =
	     state[55:32] >> state[7:3] |
	     ~(24'hFFFFFF >> state[7:3]) & {24{state_BITS_55_TO_32__q2[23]}} ;
  assign state_BITS_55_TO_32__q2 = state[55:32] ;
  assign state_BITS_79_TO_56_3_SRA_state_BITS_7_TO_3_4___d19 =
	     state[79:56] >> state[7:3] |
	     ~(24'hFFFFFF >> state[7:3]) & {24{state_BITS_79_TO_56__q1[23]}} ;
  assign state_BITS_79_TO_56__q1 = state[79:56] ;
  always@(state)
  begin
    case (state[7:3])
      5'd0:
	  CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd262144;
      5'd1:
	  CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd131072;
      5'd2:
	  CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd65536;
      5'd3:
	  CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd32768;
      5'd4:
	  CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd16384;
      5'd5: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd8192;
      5'd6: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd4096;
      5'd7: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd2048;
      5'd8: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd1024;
      5'd9: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd512;
      5'd10: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd256;
      5'd11: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd128;
      5'd12: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd64;
      5'd13: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd32;
      5'd14: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd16;
      5'd15: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd8;
      5'd16: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd4;
      5'd17: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd2;
      5'd18: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd1;
      5'd19: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 = 24'd0;
      default: CASE_state_BITS_7_TO_3_0_262144_1_131072_2_655_ETC__q3 =
		   24'b101010101010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(state)
  begin
    case (state[7:3])
      5'd0: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd3217;
      5'd1: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd1901;
      5'd2: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd1006;
      5'd3: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd511;
      5'd4: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd256;
      5'd5: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd128;
      5'd6: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd64;
      5'd7: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd32;
      5'd8: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd16;
      5'd9: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd8;
      5'd10: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd4;
      5'd11: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd2;
      5'd12, 5'd13:
	  CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd1;
      5'd14, 5'd15, 5'd16, 5'd17, 5'd18, 5'd19:
	  CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 = 24'd0;
      default: CASE_state_BITS_7_TO_3_0_3217_1_1901_2_1006_3__ETC__q4 =
		   24'b101010101010101010101010 /* unspecified value */ ;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        busy_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	state <= `BSV_ASSIGNMENT_DELAY 80'hAAAAAAAAAAAAAAAAAAAA;
      end
    else
      begin
        if (busy_reg$EN) busy_reg <= `BSV_ASSIGNMENT_DELAY busy_reg$D_IN;
	if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    busy_reg = 1'h0;
    state = 80'hAAAAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCORDIC