//
// Generated by Bluespec Compiler, version 2025.01.1-14-g36da7029 (build 36da7029)
//
// On Sun Jan 18 16:30:33 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_sin_cos                    O     1 const
// RDY_atan2                      O     1 const
// RDY_sqrt_magnitude             O     1 const
// get_sin_cos                    O    48 reg
// RDY_get_sin_cos                O     1
// get_atan2                      O    24 reg
// RDY_get_atan2                  O     1
// get_sqrt                       O    24 reg
// RDY_get_sqrt                   O     1
// busy                           O     1 reg
// RDY_busy                       O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// sin_cos_angle                  I    24
// atan2_y                        I    24
// atan2_x                        I    24
// sqrt_magnitude_x               I    24
// sqrt_magnitude_y               I    24
// EN_sin_cos                     I     1
// EN_atan2                       I     1
// EN_sqrt_magnitude              I     1
// EN_get_sin_cos                 I     1
// EN_get_atan2                   I     1
// EN_get_sqrt                    I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCORDICHighLevel(CLK,
			 RST_N,

			 sin_cos_angle,
			 EN_sin_cos,
			 RDY_sin_cos,

			 atan2_y,
			 atan2_x,
			 EN_atan2,
			 RDY_atan2,

			 sqrt_magnitude_x,
			 sqrt_magnitude_y,
			 EN_sqrt_magnitude,
			 RDY_sqrt_magnitude,

			 EN_get_sin_cos,
			 get_sin_cos,
			 RDY_get_sin_cos,

			 EN_get_atan2,
			 get_atan2,
			 RDY_get_atan2,

			 EN_get_sqrt,
			 get_sqrt,
			 RDY_get_sqrt,

			 busy,
			 RDY_busy);
  input  CLK;
  input  RST_N;

  // action method sin_cos
  input  [23 : 0] sin_cos_angle;
  input  EN_sin_cos;
  output RDY_sin_cos;

  // action method atan2
  input  [23 : 0] atan2_y;
  input  [23 : 0] atan2_x;
  input  EN_atan2;
  output RDY_atan2;

  // action method sqrt_magnitude
  input  [23 : 0] sqrt_magnitude_x;
  input  [23 : 0] sqrt_magnitude_y;
  input  EN_sqrt_magnitude;
  output RDY_sqrt_magnitude;

  // actionvalue method get_sin_cos
  input  EN_get_sin_cos;
  output [47 : 0] get_sin_cos;
  output RDY_get_sin_cos;

  // actionvalue method get_atan2
  input  EN_get_atan2;
  output [23 : 0] get_atan2;
  output RDY_get_atan2;

  // actionvalue method get_sqrt
  input  EN_get_sqrt;
  output [23 : 0] get_sqrt;
  output RDY_get_sqrt;

  // value method busy
  output busy;
  output RDY_busy;

  // signals for module outputs
  wire [47 : 0] get_sin_cos;
  wire [23 : 0] get_atan2, get_sqrt;
  wire RDY_atan2,
       RDY_busy,
       RDY_get_atan2,
       RDY_get_sin_cos,
       RDY_get_sqrt,
       RDY_sin_cos,
       RDY_sqrt_magnitude,
       busy;

  // register cordic_busy_reg
  reg cordic_busy_reg;
  wire cordic_busy_reg$D_IN, cordic_busy_reg$EN;

  // register cordic_state
  reg [79 : 0] cordic_state;
  reg [79 : 0] cordic_state$D_IN;
  wire cordic_state$EN;

  // register current_op
  reg [2 : 0] current_op;
  reg [2 : 0] current_op$D_IN;
  wire current_op$EN;

  // register operation_pending
  reg operation_pending;
  wire operation_pending$D_IN, operation_pending$EN;

  // register result_ready
  reg result_ready;
  reg result_ready$D_IN;
  wire result_ready$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_check_completion, WILL_FIRE_RL_cordic_do_iteration;

  // inputs to muxes for submodule ports
  wire [79 : 0] MUX_cordic_state$write_1__VAL_1,
		MUX_cordic_state$write_1__VAL_2,
		MUX_cordic_state$write_1__VAL_3,
		MUX_cordic_state$write_1__VAL_4;

  // remaining internal signals
  reg [23 : 0] CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2,
	       CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3;
  wire [31 : 0] IF_IF_cordic_state_BITS_2_TO_1_EQ_1_THEN_NOT_c_ETC___d36;
  wire [23 : 0] IF_cordic_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_AR_ETC___d29,
		cordic_state_BITS_55_TO_32_SRA_cordic_state_BI_ETC___d15,
		cordic_state_BITS_55_TO_32__q1,
		cordic_state_BITS_79_TO_56_3_SRA_cordic_state__ETC___d19;
  wire IF_cordic_state_BITS_2_TO_1_EQ_1_THEN_NOT_cord_ETC___d12;

  // action method sin_cos
  assign RDY_sin_cos = 1'd1 ;

  // action method atan2
  assign RDY_atan2 = 1'd1 ;

  // action method sqrt_magnitude
  assign RDY_sqrt_magnitude = 1'd1 ;

  // actionvalue method get_sin_cos
  assign get_sin_cos = { cordic_state[55:32], cordic_state[79:56] } ;
  assign RDY_get_sin_cos =
	     result_ready && current_op == 3'd2 && cordic_state[0] ;

  // actionvalue method get_atan2
  assign get_atan2 = cordic_state[31:8] ;
  assign RDY_get_atan2 =
	     result_ready && current_op == 3'd3 && cordic_state[0] ;

  // actionvalue method get_sqrt
  assign get_sqrt = cordic_state[79:56] ;
  assign RDY_get_sqrt =
	     result_ready && current_op == 3'd4 && cordic_state[0] ;

  // value method busy
  assign busy = cordic_busy_reg ;
  assign RDY_busy = 1'd1 ;

  // rule RL_check_completion
  assign WILL_FIRE_RL_check_completion =
	     operation_pending && !cordic_busy_reg && !result_ready ;

  // rule RL_cordic_do_iteration
  assign WILL_FIRE_RL_cordic_do_iteration =
	     cordic_busy_reg && !cordic_state[0] ;

  // inputs to muxes for submodule ports
  assign MUX_cordic_state$write_1__VAL_1 =
	     { sqrt_magnitude_x, sqrt_magnitude_y, 32'd2 } ;
  assign MUX_cordic_state$write_1__VAL_2 = { atan2_x, atan2_y, 32'd2 } ;
  assign MUX_cordic_state$write_1__VAL_3 =
	     { 48'h0009B7000000, sin_cos_angle, 8'd0 } ;
  assign MUX_cordic_state$write_1__VAL_4 =
	     { IF_cordic_state_BITS_2_TO_1_EQ_1_THEN_NOT_cord_ETC___d12 ?
		 cordic_state[79:56] +
		 cordic_state_BITS_55_TO_32_SRA_cordic_state_BI_ETC___d15 :
		 cordic_state[79:56] -
		 cordic_state_BITS_55_TO_32_SRA_cordic_state_BI_ETC___d15,
	       IF_cordic_state_BITS_2_TO_1_EQ_1_THEN_NOT_cord_ETC___d12 ?
		 cordic_state[55:32] -
		 cordic_state_BITS_79_TO_56_3_SRA_cordic_state__ETC___d19 :
		 cordic_state[55:32] +
		 cordic_state_BITS_79_TO_56_3_SRA_cordic_state__ETC___d19,
	       IF_IF_cordic_state_BITS_2_TO_1_EQ_1_THEN_NOT_c_ETC___d36 } ;

  // register cordic_busy_reg
  assign cordic_busy_reg$D_IN = EN_sqrt_magnitude || EN_atan2 || EN_sin_cos ;
  assign cordic_busy_reg$EN =
	     WILL_FIRE_RL_cordic_do_iteration && cordic_state[7:3] == 5'd19 ||
	     EN_sqrt_magnitude ||
	     EN_atan2 ||
	     EN_sin_cos ;

  // register cordic_state
  always@(EN_sqrt_magnitude or
	  MUX_cordic_state$write_1__VAL_1 or
	  EN_atan2 or
	  MUX_cordic_state$write_1__VAL_2 or
	  EN_sin_cos or
	  MUX_cordic_state$write_1__VAL_3 or
	  WILL_FIRE_RL_cordic_do_iteration or MUX_cordic_state$write_1__VAL_4)
  case (1'b1)
    EN_sqrt_magnitude: cordic_state$D_IN = MUX_cordic_state$write_1__VAL_1;
    EN_atan2: cordic_state$D_IN = MUX_cordic_state$write_1__VAL_2;
    EN_sin_cos: cordic_state$D_IN = MUX_cordic_state$write_1__VAL_3;
    WILL_FIRE_RL_cordic_do_iteration:
	cordic_state$D_IN = MUX_cordic_state$write_1__VAL_4;
    default: cordic_state$D_IN =
		 80'hAAAAAAAAAAAAAAAAAAAA /* unspecified value */ ;
  endcase
  assign cordic_state$EN =
	     WILL_FIRE_RL_cordic_do_iteration || EN_sin_cos || EN_atan2 ||
	     EN_sqrt_magnitude ;

  // register current_op
  always@(EN_sqrt_magnitude or EN_atan2 or EN_sin_cos)
  case (1'b1)
    EN_sqrt_magnitude: current_op$D_IN = 3'd4;
    EN_atan2: current_op$D_IN = 3'd3;
    EN_sin_cos: current_op$D_IN = 3'd2;
    default: current_op$D_IN = 3'b010 /* unspecified value */ ;
  endcase
  assign current_op$EN = EN_sin_cos || EN_atan2 || EN_sqrt_magnitude ;

  // register operation_pending
  assign operation_pending$D_IN =
	     EN_sqrt_magnitude || EN_atan2 || EN_sin_cos ;
  assign operation_pending$EN =
	     WILL_FIRE_RL_check_completion || EN_sqrt_magnitude || EN_atan2 ||
	     EN_sin_cos ;

  // register result_ready
  always@(EN_sqrt_magnitude or
	  EN_atan2 or
	  EN_sin_cos or
	  WILL_FIRE_RL_check_completion or
	  EN_get_sqrt or EN_get_atan2 or EN_get_sin_cos)
  case (1'b1)
    EN_sqrt_magnitude || EN_atan2 || EN_sin_cos: result_ready$D_IN = 1'd0;
    WILL_FIRE_RL_check_completion: result_ready$D_IN = 1'd1;
    EN_get_sqrt || EN_get_atan2 || EN_get_sin_cos: result_ready$D_IN = 1'd0;
    default: result_ready$D_IN = 1'b0 /* unspecified value */ ;
  endcase
  assign result_ready$EN =
	     EN_get_sqrt || EN_get_atan2 || EN_get_sin_cos ||
	     EN_sqrt_magnitude ||
	     EN_atan2 ||
	     EN_sin_cos ||
	     WILL_FIRE_RL_check_completion ;

  // remaining internal signals
  assign IF_IF_cordic_state_BITS_2_TO_1_EQ_1_THEN_NOT_c_ETC___d36 =
	     { IF_cordic_state_BITS_2_TO_1_EQ_1_THEN_NOT_cord_ETC___d12 ?
		 cordic_state[31:8] +
		 IF_cordic_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_AR_ETC___d29 :
		 cordic_state[31:8] -
		 IF_cordic_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_AR_ETC___d29,
	       cordic_state[7:3] + 5'd1,
	       cordic_state[2:1],
	       cordic_state[7:3] == 5'd19 } ;
  assign IF_cordic_state_BITS_2_TO_1_EQ_1_THEN_NOT_cord_ETC___d12 =
	     (cordic_state[2:1] == 2'd1) ?
	       (cordic_state[55:32] ^ 24'h800000) > 24'd8388608 :
	       cordic_state[31] ;
  assign IF_cordic_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_AR_ETC___d29 =
	     (cordic_state[2:1] == 2'd2) ?
	       CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 :
	       CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 ;
  assign cordic_state_BITS_55_TO_32_SRA_cordic_state_BI_ETC___d15 =
	     cordic_state[55:32] >> cordic_state[7:3] |
	     ~(24'hFFFFFF >> cordic_state[7:3]) &
	     {24{cordic_state_BITS_55_TO_32__q1[23]}} ;
  assign cordic_state_BITS_55_TO_32__q1 = cordic_state[55:32] ;
  assign cordic_state_BITS_79_TO_56_3_SRA_cordic_state__ETC___d19 =
	     cordic_state[79:56] >> cordic_state[7:3] |
	     ~(24'hFFFFFF >> cordic_state[7:3]) & {24{get_sqrt[23]}} ;
  always@(cordic_state)
  begin
    case (cordic_state[7:3])
      5'd0:
	  CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd262144;
      5'd1:
	  CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd131072;
      5'd2:
	  CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd65536;
      5'd3:
	  CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd32768;
      5'd4:
	  CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd16384;
      5'd5: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd8192;
      5'd6: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd4096;
      5'd7: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd2048;
      5'd8: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd1024;
      5'd9: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd512;
      5'd10: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd256;
      5'd11: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd128;
      5'd12: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd64;
      5'd13: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd32;
      5'd14: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd16;
      5'd15: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd8;
      5'd16: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd4;
      5'd17: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd2;
      5'd18: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd1;
      5'd19: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 = 24'd0;
      default: CASE_cordic_state_BITS_7_TO_3_0_262144_1_13107_ETC__q2 =
		   24'b101010101010101010101010 /* unspecified value */ ;
    endcase
  end
  always@(cordic_state)
  begin
    case (cordic_state[7:3])
      5'd0: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd3217;
      5'd1: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd1901;
      5'd2: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd1006;
      5'd3: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd511;
      5'd4: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd256;
      5'd5: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd128;
      5'd6: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd64;
      5'd7: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd32;
      5'd8: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd16;
      5'd9: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd8;
      5'd10: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd4;
      5'd11: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd2;
      5'd12, 5'd13:
	  CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd1;
      5'd14, 5'd15, 5'd16, 5'd17, 5'd18, 5'd19:
	  CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 = 24'd0;
      default: CASE_cordic_state_BITS_7_TO_3_0_3217_1_1901_2__ETC__q3 =
		   24'b101010101010101010101010 /* unspecified value */ ;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        cordic_busy_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	cordic_state <= `BSV_ASSIGNMENT_DELAY 80'hAAAAAAAAAAAAAAAAAAAA;
	current_op <= `BSV_ASSIGNMENT_DELAY 3'h2;
	operation_pending <= `BSV_ASSIGNMENT_DELAY 1'd0;
	result_ready <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (cordic_busy_reg$EN)
	  cordic_busy_reg <= `BSV_ASSIGNMENT_DELAY cordic_busy_reg$D_IN;
	if (cordic_state$EN)
	  cordic_state <= `BSV_ASSIGNMENT_DELAY cordic_state$D_IN;
	if (current_op$EN)
	  current_op <= `BSV_ASSIGNMENT_DELAY current_op$D_IN;
	if (operation_pending$EN)
	  operation_pending <= `BSV_ASSIGNMENT_DELAY operation_pending$D_IN;
	if (result_ready$EN)
	  result_ready <= `BSV_ASSIGNMENT_DELAY result_ready$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    cordic_busy_reg = 1'h0;
    cordic_state = 80'hAAAAAAAAAAAAAAAAAAAA;
    current_op = 3'h2;
    operation_pending = 1'h0;
    result_ready = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCORDICHighLevel