//
// Generated by Bluespec Compiler, version 2025.01.1-14-g36da7029 (build 36da7029)
//
// On Sat Dec 13 17:12:53 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// RDY_start                      O     1 const
// getResult                      O   104 reg
// RDY_getResult                  O     1 reg
// busy                           O     1 reg
// RDY_busy                       O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// start_x_init                   I    32
// start_y_init                   I    32
// start_z_init                   I    32
// start_mode                     I     2
// EN_start                       I     1
// EN_getResult                   I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCORDIC(CLK,
		RST_N,

		start_x_init,
		start_y_init,
		start_z_init,
		start_mode,
		EN_start,
		RDY_start,

		EN_getResult,
		getResult,
		RDY_getResult,

		busy,
		RDY_busy);
  input  CLK;
  input  RST_N;

  // action method start
  input  [31 : 0] start_x_init;
  input  [31 : 0] start_y_init;
  input  [31 : 0] start_z_init;
  input  [1 : 0] start_mode;
  input  EN_start;
  output RDY_start;

  // actionvalue method getResult
  input  EN_getResult;
  output [103 : 0] getResult;
  output RDY_getResult;

  // value method busy
  output busy;
  output RDY_busy;

  // signals for module outputs
  wire [103 : 0] getResult;
  wire RDY_busy, RDY_getResult, RDY_start, busy;

  // register busy_reg
  reg busy_reg;
  wire busy_reg$D_IN, busy_reg$EN;

  // register state
  reg [103 : 0] state;
  wire [103 : 0] state$D_IN;
  wire state$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_do_iteration;

  // inputs to muxes for submodule ports
  wire [103 : 0] MUX_state$write_1__VAL_1, MUX_state$write_1__VAL_2;

  // remaining internal signals
  reg [31 : 0] CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3,
	       CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4;
  wire [39 : 0] IF_IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BI_ETC___d36;
  wire [31 : 0] IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_14739_ETC___d29,
		state_BITS_103_TO_72_3_SRA_state_BITS_7_TO_3_4___d19,
		state_BITS_103_TO_72__q1,
		state_BITS_71_TO_40_SRA_state_BITS_7_TO_3_4___d15,
		state_BITS_71_TO_40__q2;
  wire IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12;

  // action method start
  assign RDY_start = 1'd1 ;

  // actionvalue method getResult
  assign getResult = state ;
  assign RDY_getResult = state[0] ;

  // value method busy
  assign busy = busy_reg ;
  assign RDY_busy = 1'd1 ;

  // rule RL_do_iteration
  assign WILL_FIRE_RL_do_iteration = busy_reg && !state[0] ;

  // inputs to muxes for submodule ports
  assign MUX_state$write_1__VAL_1 =
	     { start_x_init,
	       start_y_init,
	       start_z_init,
	       5'd0,
	       start_mode,
	       1'd0 } ;
  assign MUX_state$write_1__VAL_2 =
	     { IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 ?
		 state[103:72] +
		 state_BITS_71_TO_40_SRA_state_BITS_7_TO_3_4___d15 :
		 state[103:72] -
		 state_BITS_71_TO_40_SRA_state_BITS_7_TO_3_4___d15,
	       IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 ?
		 state[71:40] -
		 state_BITS_103_TO_72_3_SRA_state_BITS_7_TO_3_4___d19 :
		 state[71:40] +
		 state_BITS_103_TO_72_3_SRA_state_BITS_7_TO_3_4___d19,
	       IF_IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BI_ETC___d36 } ;

  // register busy_reg
  assign busy_reg$D_IN = EN_start ;
  assign busy_reg$EN =
	     WILL_FIRE_RL_do_iteration && state[7:3] == 5'd31 || EN_start ;

  // register state
  assign state$D_IN =
	     EN_start ? MUX_state$write_1__VAL_1 : MUX_state$write_1__VAL_2 ;
  assign state$EN = WILL_FIRE_RL_do_iteration || EN_start ;

  // remaining internal signals
  assign IF_IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BI_ETC___d36 =
	     { IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 ?
		 state[39:8] +
		 IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_14739_ETC___d29 :
		 state[39:8] -
		 IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_14739_ETC___d29,
	       state[7:3] + 5'd1,
	       state[2:1],
	       state[7:3] == 5'd31 } ;
  assign IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 =
	     (state[2:1] == 2'd1) ?
	       (state[71:40] ^ 32'h80000000) > 32'h80000000 :
	       state[39] ;
  assign IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_14739_ETC___d29 =
	     (state[2:1] == 2'd2) ?
	       CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 :
	       CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 ;
  assign state_BITS_103_TO_72_3_SRA_state_BITS_7_TO_3_4___d19 =
	     state[103:72] >> state[7:3] |
	     ~(32'hFFFFFFFF >> state[7:3]) &
	     {32{state_BITS_103_TO_72__q1[31]}} ;
  assign state_BITS_103_TO_72__q1 = state[103:72] ;
  assign state_BITS_71_TO_40_SRA_state_BITS_7_TO_3_4___d15 =
	     state[71:40] >> state[7:3] |
	     ~(32'hFFFFFFFF >> state[7:3]) &
	     {32{state_BITS_71_TO_40__q2[31]}} ;
  assign state_BITS_71_TO_40__q2 = state[71:40] ;
  always@(state)
  begin
    case (state[7:3])
      5'd0:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 =
	      32'd147391456;
      5'd1:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 =
	      32'd69254785;
      5'd2:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 =
	      32'd34408521;
      5'd3:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 =
	      32'd17119964;
      5'd4:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 =
	      32'd8567219;
      5'd5:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 =
	      32'd4282395;
      5'd6:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 =
	      32'd2796722;
      5'd7:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 =
	      32'd1398361;
      5'd8:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd699051;
      5'd9:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd349611;
      5'd10:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd174763;
      5'd11:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd87381;
      5'd12:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd43691;
      5'd13:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd21845;
      5'd14:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd10923;
      5'd15:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd5461;
      5'd16:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd2731;
      5'd17:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd1365;
      5'd18: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd683;
      5'd19: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd341;
      5'd20: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd171;
      5'd21: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd85;
      5'd22: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd43;
      5'd23: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd21;
      5'd24: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd11;
      5'd25: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd5;
      5'd26: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd2;
      5'd27: CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd1;
      5'd28, 5'd29, 5'd30, 5'd31:
	  CASE_state_BITS_7_TO_3_0_147391456_1_69254785__ETC__q3 = 32'd0;
    endcase
  end
  always@(state)
  begin
    case (state[7:3])
      5'd0:
	  CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd51471;
      5'd1:
	  CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd30385;
      5'd2:
	  CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd16054;
      5'd3: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd8149;
      5'd4: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd4091;
      5'd5: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd2047;
      5'd6: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd1024;
      5'd7: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd512;
      5'd8: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd256;
      5'd9: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd128;
      5'd10: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd64;
      5'd11: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd32;
      5'd12: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd16;
      5'd13: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd8;
      5'd14: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd4;
      5'd15: CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd2;
      5'd16, 5'd17:
	  CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd1;
      5'd18,
      5'd19,
      5'd20,
      5'd21,
      5'd22,
      5'd23,
      5'd24,
      5'd25,
      5'd26,
      5'd27,
      5'd28,
      5'd29,
      5'd30,
      5'd31:
	  CASE_state_BITS_7_TO_3_0_51471_1_30385_2_16054_ETC__q4 = 32'd0;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        busy_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	state <= `BSV_ASSIGNMENT_DELAY 104'hAAAAAAAAAAAAAAAAAAAAAAAAAA;
      end
    else
      begin
        if (busy_reg$EN) busy_reg <= `BSV_ASSIGNMENT_DELAY busy_reg$D_IN;
	if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    busy_reg = 1'h0;
    state = 104'hAAAAAAAAAAAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCORDIC

