//
// Generated by Bluespec Compiler, version 2025.01.1-14-g36da7029 (build 36da7029)
//
// On Fri Jan 16 17:45:37 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_start                      O     1 const
// getResult                      O    55 reg
// RDY_getResult                  O     1 reg
// busy                           O     1 reg
// RDY_busy                       O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// start_x_init                   I    16
// start_y_init                   I    16
// start_z_init                   I    16
// start_mode                     I     2
// EN_start                       I     1
// EN_getResult                   I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCORDIC(CLK,
		RST_N,

		start_x_init,
		start_y_init,
		start_z_init,
		start_mode,
		EN_start,
		RDY_start,

		EN_getResult,
		getResult,
		RDY_getResult,

		busy,
		RDY_busy);
  input  CLK;
  input  RST_N;

  // action method start
  input  [15 : 0] start_x_init;
  input  [15 : 0] start_y_init;
  input  [15 : 0] start_z_init;
  input  [1 : 0] start_mode;
  input  EN_start;
  output RDY_start;

  // actionvalue method getResult
  input  EN_getResult;
  output [54 : 0] getResult;
  output RDY_getResult;

  // value method busy
  output busy;
  output RDY_busy;

  // signals for module outputs
  wire [54 : 0] getResult;
  wire RDY_busy, RDY_getResult, RDY_start, busy;

  // register busy_reg
  reg busy_reg;
  wire busy_reg$D_IN, busy_reg$EN;

  // register state
  reg [54 : 0] state;
  wire [54 : 0] state$D_IN;
  wire state$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_do_iteration;

  // inputs to muxes for submodule ports
  wire [54 : 0] MUX_state$write_1__VAL_1, MUX_state$write_1__VAL_2;

  // remaining internal signals
  reg [15 : 0] CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3,
	       CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4;
  wire [22 : 0] IF_IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BI_ETC___d36;
  wire [15 : 0] IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_16384_ETC___d29,
		state_BITS_38_TO_23_SRA_state_BITS_6_TO_3_4___d15,
		state_BITS_38_TO_23__q2,
		state_BITS_54_TO_39_3_SRA_state_BITS_6_TO_3_4___d19,
		state_BITS_54_TO_39__q1;
  wire IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12;

  // action method start
  assign RDY_start = 1'd1 ;

  // actionvalue method getResult
  assign getResult = state ;
  assign RDY_getResult = state[0] ;

  // value method busy
  assign busy = busy_reg ;
  assign RDY_busy = 1'd1 ;

  // rule RL_do_iteration
  assign WILL_FIRE_RL_do_iteration = busy_reg && !state[0] ;

  // inputs to muxes for submodule ports
  assign MUX_state$write_1__VAL_1 =
	     { start_x_init,
	       start_y_init,
	       start_z_init,
	       4'd0,
	       start_mode,
	       1'd0 } ;
  assign MUX_state$write_1__VAL_2 =
	     { IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 ?
		 state[54:39] +
		 state_BITS_38_TO_23_SRA_state_BITS_6_TO_3_4___d15 :
		 state[54:39] -
		 state_BITS_38_TO_23_SRA_state_BITS_6_TO_3_4___d15,
	       IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 ?
		 state[38:23] -
		 state_BITS_54_TO_39_3_SRA_state_BITS_6_TO_3_4___d19 :
		 state[38:23] +
		 state_BITS_54_TO_39_3_SRA_state_BITS_6_TO_3_4___d19,
	       IF_IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BI_ETC___d36 } ;

  // register busy_reg
  assign busy_reg$D_IN = EN_start ;
  assign busy_reg$EN =
	     WILL_FIRE_RL_do_iteration && state[6:3] == 4'd15 || EN_start ;

  // register state
  assign state$D_IN =
	     EN_start ? MUX_state$write_1__VAL_1 : MUX_state$write_1__VAL_2 ;
  assign state$EN = WILL_FIRE_RL_do_iteration || EN_start ;

  // remaining internal signals
  assign IF_IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BI_ETC___d36 =
	     { IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 ?
		 state[22:7] +
		 IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_16384_ETC___d29 :
		 state[22:7] -
		 IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_16384_ETC___d29,
	       state[6:3] + 4'd1,
	       state[2:1],
	       state[6:3] == 4'd15 } ;
  assign IF_state_BITS_2_TO_1_EQ_1_THEN_NOT_state_BITS__ETC___d12 =
	     (state[2:1] == 2'd1) ?
	       (state[38:23] ^ 16'h8000) > 16'd32768 :
	       state[22] ;
  assign IF_state_BITS_2_TO_1_EQ_2_4_THEN_SEL_ARR_16384_ETC___d29 =
	     (state[2:1] == 2'd2) ?
	       CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 :
	       CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 ;
  assign state_BITS_38_TO_23_SRA_state_BITS_6_TO_3_4___d15 =
	     state[38:23] >> state[6:3] |
	     ~(16'hFFFF >> state[6:3]) & {16{state_BITS_38_TO_23__q2[15]}} ;
  assign state_BITS_38_TO_23__q2 = state[38:23] ;
  assign state_BITS_54_TO_39_3_SRA_state_BITS_6_TO_3_4___d19 =
	     state[54:39] >> state[6:3] |
	     ~(16'hFFFF >> state[6:3]) & {16{state_BITS_54_TO_39__q1[15]}} ;
  assign state_BITS_54_TO_39__q1 = state[54:39] ;
  always@(state)
  begin
    case (state[6:3])
      4'd0:
	  CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd16384;
      4'd1: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd8192;
      4'd2: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd4096;
      4'd3: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd2048;
      4'd4: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd1024;
      4'd5: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd512;
      4'd6: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd256;
      4'd7: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd128;
      4'd8: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd64;
      4'd9: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd32;
      4'd10: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd16;
      4'd11: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd8;
      4'd12: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd4;
      4'd13: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd2;
      4'd14: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd1;
      4'd15: CASE_state_BITS_6_TO_3_0_16384_1_8192_2_4096_3_ETC__q3 = 16'd0;
    endcase
  end
  always@(state)
  begin
    case (state[6:3])
      4'd0: CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd201;
      4'd1: CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd119;
      4'd2: CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd63;
      4'd3: CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd32;
      4'd4: CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd16;
      4'd5: CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd8;
      4'd6: CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd4;
      4'd7: CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd2;
      4'd8, 4'd9:
	  CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd1;
      4'd10, 4'd11, 4'd12, 4'd13, 4'd14, 4'd15:
	  CASE_state_BITS_6_TO_3_0_201_1_119_2_63_3_32_4_ETC__q4 = 16'd0;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        busy_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	state <= `BSV_ASSIGNMENT_DELAY 55'h2AAAAAAAAAAAAA;
      end
    else
      begin
        if (busy_reg$EN) busy_reg <= `BSV_ASSIGNMENT_DELAY busy_reg$D_IN;
	if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    busy_reg = 1'h0;
    state = 55'h2AAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCORDIC